// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using rest_api_dotnet_core.Data;

namespace rest_api_dotnet_core.Migrations
{
    [DbContext(typeof(ApiDbContext))]
    [Migration("20221113222840_add_comments")]
    partial class add_comments
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.17")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("rest_api_dotnet_core.Models.Comment", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Text")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Comments");

                    b.HasData(
                        new
                        {
                            Id = new Guid("95a96afc-a1c1-4337-b0a7-a44d6a9f959d"),
                            CreatedAt = new DateTime(2022, 11, 13, 23, 28, 39, 385, DateTimeKind.Local).AddTicks(878),
                            Text = "Le lorem ipsum est, en imprimerie, une suite de mots sans signification utilisée à titre provisoire pour calibrer une mise en page"
                        },
                        new
                        {
                            Id = new Guid("007772ce-ba6b-4071-b356-9503d92d166e"),
                            CreatedAt = new DateTime(2022, 11, 13, 23, 28, 39, 388, DateTimeKind.Local).AddTicks(3518),
                            Text = "Le lorem ipsum est, en imprimerie, une suite de mots sans signification utilisée"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
